import React from 'react'
import {Provider} from './Provider'
import '../styles/globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <h1>header</h1>
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  )
}
